### ISSUE TITLE
No nets part

### ISSUE THREAD

**Issue by zhangyuzhen1990** [TalkUHulk/yolov3-TT100k#1]
The code of yolo3_TT100k has no nets part

**Comment by Mushero** [comment]
Yes, have you solved the problem yet

**Comment by Mushero** [comment]
Yes, no nets! have you solved the problem yet?

**Comment by TalkUHulk** [comment]
> Yes, no nets! have you solved the problem yet?

https://github.com/bubbliiiing/yolo3-pytorch/tree/master/nets

**Comment by Mushero** [comment]
Thanks!
